// Auto-generated enum for civBonuses indices
// Maps to descriptions in misc/strings.txt

#ifndef CIV_BONUS_ENUM_H
#define CIV_BONUS_ENUM_H

enum CivBonusIndex {
    CIV_BONUS_0_BONUS_0 = 0, // BONUS_0
    CIV_BONUS_1_TOWN_CENTERS_COST_50_WOOD_STARTING_IN = 1, // Town Centers cost -50% wood starting in the Castle Age
    CIV_BONUS_2_FOOT_ARCHERS_EXCEPT_SKIRMISHERS_1_RANGE_IN = 2, // Foot archers (except skirmishers) +1 range in Castle and Imperial Age (+2 total)
    CIV_BONUS_3_SHEPHERDS_WORK_25_FASTER = 3, // Shepherds work 25% faster
    CIV_BONUS_4_CASTLES_COST_15_IN_CASTLE_25_IN_IMPERIAL_AGE = 4, // Castles cost -15% in Castle, -25% in Imperial Age
    CIV_BONUS_5_MOUNTED_UNITS_20_HIT_POINTS_STARTING_IN_FEUDAL_AGE = 5, // Mounted units +20% hit points starting in Feudal Age
    CIV_BONUS_6_FORAGERS_WORK_10_FASTER = 6, // Foragers work 10% faster
    CIV_BONUS_7_LOOM_CAN_BE_RESEARCHED_INSTANTLY = 7, // Loom can be researched instantly
    CIV_BONUS_8_VILLAGERS_5_ATTACK_VS_WILD_BOAR_HUNTERS = 8, // Villagers +5 attack vs. wild boar; hunters carry +15 meat; hunt contains +20% meat
    CIV_BONUS_9_10_POPULATION_IN_IMPERIAL_AGE = 9, // +10 population in Imperial Age
    CIV_BONUS_10_INFANTRY_1_ATTACK_VS_BUILDINGS_PER_AGE = 10, // Infantry +1 attack vs. buildings per age (starting from Feudal Age)
    CIV_BONUS_11_INFANTRY_COST_15_IN_DARK_20_IN = 11, // Infantry cost -15% in Dark, -20% in Feudal, -25% in Castle, -30% in Imperial Age
    CIV_BONUS_12_MONKS_DOUBLE_HEALING_RANGE = 12, // Monks double healing range
    CIV_BONUS_13_TOWERS_GARRISON_2X_UNITS_TOWN_CENTERS_GARRISON_10 = 13, // Towers garrison 2x units; Town Centers garrison +10
    CIV_BONUS_14_FARMS_COST_40 = 14, // Farms cost -40%
    CIV_BONUS_15_BARRACKS_AND_STABLE_UNITS_1_ARMOR_IN = 15, // Barracks and Stable units +1 armor in Castle and Imperial Age (+2 total)
    CIV_BONUS_16_ECONOMIC_DROP_OFF_BUILDINGS_COST_50 = 16, // Economic drop-off buildings cost -50%
    CIV_BONUS_17_FISHING_SHIPS_2X_HIT_POINTS_2P_ARMOR = 17, // Fishing Ships 2x hit points; +2P armor; work rate +5% Dark, +10% Feudal, +15% Castle, +20% Imperial Age
    CIV_BONUS_18_INFANTRY_ATTACK_33_FASTER_STARTING_IN_FEUDAL_AGE = 18, // Infantry attack 33% faster starting in Feudal Age
    CIV_BONUS_19_START_WITH_3_VILLAGERS_50_WOOD_200 = 19, // Start with +3 villagers, -50 wood, -200 food; Town Centers support 15 population and +7 LOS
    CIV_BONUS_20_DEMOLITION_SHIPS_50_HIT_POINTS = 20, // Demolition ships +50% hit points
    CIV_BONUS_21_TECHNOLOGIES_COST_5_FEUDAL_10_CASTLE_15 = 21, // Technologies cost -5% Feudal, -10% Castle, -15% Imperial Age
    CIV_BONUS_22_BUILDINGS_10_HP_DARK_20_FEUDAL_30 = 22, // Buildings +10% HP Dark, +20% Feudal, +30% Castle, +40% Imperial Age
    CIV_BONUS_23_FIRE_SHIPS_ATTACK_25_FASTER = 23, // Fire ships attack 25% faster
    CIV_BONUS_24_CAMEL_RIDERS_SKIRMISHERS_PIKEMEN_HALBERDIERS_COST_25 = 24, // Camel Riders, Skirmishers, Pikemen, Halberdiers cost -25%
    CIV_BONUS_25_START_WITH_50_WOOD_FOOD = 25, // Start with +50 wood, food
    CIV_BONUS_26_TOWN_CENTER_DOCK_2X_HIT_POINTS = 26, // Town Center, Dock 2x hit points
    CIV_BONUS_27_TOWN_CENTER_DOCK_WORK_RATE_5_DARK = 27, // Town Center, Dock work rate +5% Dark, +10% Feudal, +15% Castle, +20% Imperial Age
    CIV_BONUS_28_MARKET_COSTS_100_WOOD_MARKET_TRADE_COST_ONLY_5 = 28, // Market costs -100 wood; market trade cost only 5%
    CIV_BONUS_29_TRANSPORT_SHIPS_2X_HIT_POINTS_20_CARRY_CAPACITY = 29, // Transport Ships 2x hit points, +20 carry capacity
    CIV_BONUS_30_GALLEYS_ATTACK_25_FASTER = 30, // Galleys attack 25% faster
    CIV_BONUS_31_CAMEL_UNITS_25_HIT_POINTS = 31, // Camel units +25% hit points
    CIV_BONUS_32_GUNPOWDER_UNITS_25_HIT_POINTS = 32, // Gunpowder units +25% hit points
    CIV_BONUS_33_GOLD_MINERS_WORK_20_FASTER = 33, // Gold miners work 20% faster
    CIV_BONUS_34_SCOUT_CAVALRY_LIGHT_CAVALRY_HUSSAR_1_PIERCE_ARMOR = 34, // Scout Cavalry, Light Cavalry, Hussar +1 pierce armor
    CIV_BONUS_35_WARSHIPS_COST_15_FEUDAL_AGE_15_CASTLE = 35, // Warships cost -15% Feudal Age, -15% Castle Age, -20% Imperial Age
    CIV_BONUS_36_INFANTRY_20_HIT_POINTS_STARTING_IN_FEUDAL_AGE = 36, // Infantry +20% hit points starting in Feudal Age
    CIV_BONUS_37_CAVALRY_ARCHERS_FIRE_25_FASTER = 37, // Cavalry archers fire 25% faster
    CIV_BONUS_38_HUNTERS_WORK_40_FASTER = 38, // Hunters work 40% faster
    CIV_BONUS_39_LIGHT_CAVALRY_HUSSARS_STEPPE_LANCERS_20_30 = 39, // Light Cavalry, Hussars, Steppe Lancers +20/30% hit points in Castle/Imperial Age
    CIV_BONUS_40_INFANTRY_MOVES_5_10_15_20_FASTER = 40, // Infantry moves +5/10/15/20% faster in Dark/Feudal/Castle/Imperial Age
    CIV_BONUS_41_LUMBERJACKS_WORK_15_FASTER = 41, // Lumberjacks work 15% faster
    CIV_BONUS_42_SIEGE_UNITS_FIRE_25_FASTER = 42, // Siege units fire 25% faster
    CIV_BONUS_43_CAN_STEAL_SHEEP_AND_SHEEP_WITHIN_ONE = 43, // Can steal sheep, and sheep within one unit's LoS cannot be stolen
    CIV_BONUS_44_MISSIONARIES_CAN_BE_TRAINED_IN_MONASTERIES = 44, // Missionaries can be trained in monasteries
    CIV_BONUS_45_START_WITH_50_GOLD = 45, // Start with +50 gold
    CIV_BONUS_46_5_MONK_HIT_POINTS_FOR_EACH_MONASTERY_TECHNOLOGY = 46, // +5 Monk hit points for each Monastery technology
    CIV_BONUS_47_START_WITH_1_VILLAGER_BUT_50_FOOD = 47, // Start with +1 villager, but -50 food
    CIV_BONUS_48_CAVALRY_ARCHERS_COST_10_CASTLE_20_IMPERIAL_AGE = 48, // Cavalry Archers cost -10% Castle, -20% Imperial Age
    CIV_BONUS_49_RANGED_SOLDIERS_AND_INFANTRY_COST_50_WOOD = 49, // Ranged Soldiers and Infantry cost -50% wood
    CIV_BONUS_50_ARCHER_ARMOR_UPGRADES_FREE = 50, // Archer armor upgrades free
    CIV_BONUS_51_CAN_TRAIN_TURTLE_SHIPS_IN_DOCKS = 51, // Can train Turtle Ships in docks
    CIV_BONUS_52_CAN_RECRUIT_LONGBOATS_FROM_DOCKS = 52, // Can recruit Longboats from docks
    CIV_BONUS_53_GUNPOWDER_UNITS_COST_20 = 53, // Gunpowder units cost -20%
    CIV_BONUS_54_CAN_UPGRADE_HEAVY_CAMEL_RIDERS_TO_IMPERIAL = 54, // Can upgrade Heavy Camel Riders to Imperial Camel Riders
    CIV_BONUS_55_FISHERMEN_WORK_10_FASTER = 55, // Fishermen work 10% faster
    CIV_BONUS_56_STABLE_UNITS_1P_ARMOR_IN_CASTLE_AND = 56, // Stable units +1P armor in Castle and Imperial Age (+2 total)
    CIV_BONUS_57_VILLAGERS_COST_8_DARK_13_FEUDAL_18 = 57, // Villagers cost -8% Dark, -13% Feudal, -18% Castle, -23% Imperial Age
    CIV_BONUS_58_MILITARY_UNITS_COST_10_15_20_25 = 58, // Military units cost -10, 15, 20, 25% food in Dark, Feudal, Castle, Imperial
    CIV_BONUS_59_BUILDINGS_COST_15_STONE = 59, // Buildings cost -15% stone
    CIV_BONUS_60_HOUSES_SUPPORT_10_POPULATION = 60, // Houses support 10 population
    CIV_BONUS_61_VILLAGERS_AFFECTED_BY_BLACKSMITH_UPGRADES_STARTING_IN = 61, // Villagers affected by Blacksmith upgrades starting in the Castle Age
    CIV_BONUS_62_CAN_RECRUIT_SLINGERS_FROM_ARCHERY_RANGES = 62, // Can recruit slingers from Archery Ranges
    CIV_BONUS_63_VILLAGERS_KILL_WOLVES_WITH_1_STRIKE = 63, // Villagers kill wolves with 1 strike
    CIV_BONUS_64_SCOUT_CAVALRY_LIGHT_CAVALRY_HUSSAR_COST_15 = 64, // Scout Cavalry, Light Cavalry, Hussar cost -15%
    CIV_BONUS_65_SIEGE_WORKSHOP_UNITS_15_CHEAPER = 65, // Siege Workshop units 15% cheaper
    CIV_BONUS_66_ALL_UNITS_COST_20_GOLD = 66, // All units cost -20% gold
    CIV_BONUS_67_FORAGERS_GENERATE_A_TRICKLE_OF_WOOD_33 = 67, // Foragers generate a trickle of wood (33%)
    CIV_BONUS_68_SHIPS_10_HP = 68, // Ships +10% HP
    CIV_BONUS_69_CAN_BUILD_FEITORIA_IN_IMPERIAL_AGE = 69, // Can build Feitoria in Imperial Age
    CIV_BONUS_70_CAN_BUILD_CARAVELS_IN_DOCKS = 70, // Can build Caravels in docks
    CIV_BONUS_71_FOOT_ARCHERS_FIRE_18_FASTER = 71, // Foot archers fire 18% faster
    CIV_BONUS_72_RECEIVE_100_GOLD_100_FOOD_WHEN_ADVANCING = 72, // Receive +100 gold, +100 food when advancing to the next age
    CIV_BONUS_73_PIKEMAN_UPGRADE_FREE = 73, // Pikeman upgrade free
    CIV_BONUS_74_BUILDINGS_COST_15_WOOD = 74, // Buildings cost -15% wood
    CIV_BONUS_75_BARRACKS_UNITS_1_PIERCE_ARMOR_PER_AGE = 75, // Barracks units +1 pierce armor per age (starting from Feudal Age)
    CIV_BONUS_76_VILLAGERS_DROP_OFF_10_MORE_GOLD = 76, // Villagers drop off 10% more gold
    CIV_BONUS_77_VILLAGERS_MOVE_5_FASTER_IN_DARK_AGE = 77, // Villagers move 5% faster in Dark Age, 10% faster in Feudal Age
    CIV_BONUS_78_SHIPS_MOVE_10_FASTER = 78, // Ships move 10% faster
    CIV_BONUS_79_STABLE_UNITS_COST_15_IN_CASTLE_20_IN_IMPERIAL_AGE = 79, // Stable units cost -15% in Castle, -20% in Imperial Age
    CIV_BONUS_80_MELEE_ELEPHANT_UNITS_MOVE_10_FASTER = 80, // Melee elephant units move 10% faster
    CIV_BONUS_81_VILLAGERS_CAN_GARRISON_IN_HOUSES = 81, // Villagers can garrison in Houses
    CIV_BONUS_82_NO_BUILDINGS_REQUIRED_TO_ADVANCE_TO_THE = 82, // No buildings required to advance to the next age or to unlock other buildings
    CIV_BONUS_83_ADVANCE_TO_THE_NEXT_AGE_66_FASTER = 83, // Advance to the next age 66% faster
    CIV_BONUS_84_ELEPHANT_UNITS_COST_25_CASTLE_35_IN_IMPERIAL_AGE = 84, // Elephant units cost -25% Castle, -35% in Imperial Age
    CIV_BONUS_85_FISH_TRAPS_COST_33_AND_PROVIDE_200_FOOD = 85, // Fish Traps cost -33% and provide +200% food
    CIV_BONUS_86_FOOT_ARCHERS_AND_CONDOTTIERI_1_MELEE_1 = 86, // Foot Archers and Condottieri +1 melee/+1 pierce armor
    CIV_BONUS_87_LUMBER_CAMP_UPGRADES_FREE = 87, // Lumber Camp upgrades free
    CIV_BONUS_88_INFANTRY_1_ATTACK_PER_AGE_STARTING_IN = 88, // Infantry +1 attack per age (starting in the Feudal Age)
    CIV_BONUS_89_MONASTERY_TECHNOLOGIES_COST_50 = 89, // Monastery technologies cost -50%
    CIV_BONUS_90_ENEMY_POSITIONS_ARE_REVEALED_AT_THE_START = 90, // Enemy positions are revealed at the start of the game
    CIV_BONUS_91_ARCHERY_RANGE_UNITS_AND_FIRE_LANCERS_20_HP = 91, // Archery Range units and Fire Lancers +20% HP
    CIV_BONUS_92_MILITIA_LINE_UPGRADES_FREE = 92, // Militia-line upgrades free
    CIV_BONUS_93_TOWN_CENTERS_COST_50_STONE_STARTING_IN = 93, // Town Centers cost -50% stone starting in the Castle Age
    CIV_BONUS_94_CAN_BUILD_KREPOST = 94, // Can build Krepost
    CIV_BONUS_95_LIVESTOCK_ANIMALS_LAST_50_LONGER = 95, // Livestock animals last +50% longer
    CIV_BONUS_96_UNITS_DEAL_25_DAMAGE_WHEN_FIGHTING_FROM = 96, // Units deal +25% damage when fighting from higher elevation
    CIV_BONUS_97_THUMB_RING_PARTHIAN_TACTICS_FREE = 97, // Thumb Ring, Parthian Tactics free
    CIV_BONUS_98_MOUNTED_UNITS_5_FASTER_EACH_AGE_STARTING = 98, // Mounted units 5% faster each age (starting in Feudal Age)
    CIV_BONUS_99_ADDITIONAL_TOWN_CENTER_CAN_BE_BUILT_IN = 99, // Additional Town Center can be built in the Feudal Age
    CIV_BONUS_100_SIEGE_WORKSHOP_AND_BATTERING_RAM_AVAILABLE_IN = 100, // Siege Workshop and Battering Ram available in the Feudal Age; Capped Ram upgrade available in Castle Age
    CIV_BONUS_101_RECEIVE_100_FOOD_PER_TOWN_CENTER = 101, // Receive +100 food per Town Center
    CIV_BONUS_102_SPEARMEN_AND_SKIRMISHERS_MOVE_10_FASTER = 102, // Spearmen and Skirmishers move 10% faster
    CIV_BONUS_103_EACH_GARRISONED_RELIC_GIVES_1_ATTACK_TO = 103, // Each garrisoned relic gives +1 attack to Knights and Unique Unit (maximum +4)
    CIV_BONUS_104_CAVALIER_UPGRADE_AVAILABLE_IN_CASTLE_AGE = 104, // Cavalier upgrade available in Castle Age
    CIV_BONUS_105_GUNPOWDER_UNITS_25_ATTACK = 105, // Gunpowder units +25% attack
    CIV_BONUS_106_ECONOMIC_UPGRADES_COST_33_FOOD_AND_AVAILABLE = 106, // Economic upgrades cost -33% food and available one age earlier
    CIV_BONUS_107_FORTIFICATIONS_BUILT_50_TOWN_CENTERS_BUILT_100 = 107, // Fortifications built 50%, Town Centers built 100% faster
    CIV_BONUS_108_SOLDIERS_RECEIVE_33_LESS_BONUS_DAMAGE = 108, // Soldiers receive 33% less bonus damage
    CIV_BONUS_109_FARM_UPGRADES_PROVIDE_125_ADDITIONAL_FOOD = 109, // Farm upgrades provide +125% additional food
    CIV_BONUS_120_CONSCRIPTION_FREE = 120, // Conscription free
    CIV_BONUS_133_RESOURCES_LAST_15_LONGER = 133, // Resources last 15% longer
    CIV_BONUS_134_FOOT_ARCHERS_AND_SKIRMISHERS_COST_10_FEUDAL = 134, // Foot archers and skirmishers cost -10% Feudal, -20% Castle, -30% Imperial Age
    CIV_BONUS_135_LUMBERJACKS_GENERATE_FOOD_IN_ADDITION_TO_WOOD = 135, // Lumberjacks generate food in addition to wood
    CIV_BONUS_139_STABLE_TECHNOLOGIES_COST_50 = 139, // Stable technologies cost -50%
    CIV_BONUS_140_NEW_TOWN_CENTERS_SPAWN_2_SHEEP_STARTING = 140, // New Town Centers spawn 2 sheep starting in the Castle Age
    CIV_BONUS_142_VILLAGERS_3_HP_PER_ECONOMIC_TECH_RESEARCHED = 142, // Villagers +3 HP per economic tech researched
    CIV_BONUS_175_START_WITH_150_WOOD = 175, // Start with +150 wood
    CIV_BONUS_192_LAND_EXPLOSIVE_UNITS_2X_HP = 192, // Land explosive units 2x HP
    CIV_BONUS_193_TOWN_CENTERS_SPAWN_2_VILLAGERS_WHEN_THE = 193, // Town Centers spawn 2 villagers when the next Age is reached
    CIV_BONUS_204_INFANTRY_1_ATTACK_VS_VILLAGERS_PER_AGE = 204, // Infantry +1 attack vs. villagers per age (starting in Dark Age)
    CIV_BONUS_209_ELEPHANT_UNITS_ATTACK_25_FASTER = 209, // Elephant units attack 25% faster
    CIV_BONUS_211_RECEIVE_50_FOOD_50_WOOD_50_STONE = 211, // Receive +50 food, +50 wood, +50 stone, +50 gold when advancing to the next age
    CIV_BONUS_218_GUNPOWDER_UNITS_MOVE_20_FASTER = 218, // Gunpowder units move 20% faster
    CIV_BONUS_220_MONK_UNITS_MOVE_20_FASTER = 220, // Monk units move 20% faster
    CIV_BONUS_221_MELEE_CAVALRY_GAIN_2_BONUS_DAMAGE_VS_SKIRMISHERS = 221, // Melee Cavalry gain +2 bonus damage vs Skirmishers
    CIV_BONUS_226_SIEGE_TOWERS_TRAIN_100_FASTER = 226, // Siege Towers train 100% faster
    CIV_BONUS_229_WARSHIPS_10_ATTACK_VS_VILLAGERS = 229, // Warships +10 attack vs. villagers
    CIV_BONUS_239_BERRIES_CONTAIN_35_MORE_FOOD = 239, // Berries contain +35% more food
    CIV_BONUS_247_SIEGE_UNITS_1_PIERCE_ARMOR_IN_CASTLE = 247, // Siege units +1 pierce armor in Castle and Imperial (+2 total)
    CIV_BONUS_257_SCOUTS_LIGHT_CAVALRY_HUSSAR_4_ATTACK_VS = 257, // Scouts, Light Cavalry, Hussar +4 attack vs. stone defenses
    CIV_BONUS_269_BOMBARD_TOWERS_DEAL_EXTRA_DAMAGE_TO_RAMS = 269, // Bombard towers deal extra damage to rams
    CIV_BONUS_270_TOWERS_DEAL_EXTRA_DAMAGE_TO_CAVALRY = 270, // Towers deal extra damage to cavalry
    CIV_BONUS_280_EACH_MONASTERY_TECHNOLOGY_RESEARCHED_BRINGS_A_MONK = 280, // Each monastery technology researched brings a monk to your cause
    CIV_BONUS_281_FOLWARK_REPLACES_MILL = 281, // Folwark replaces Mill
    CIV_BONUS_282_STONE_MINERS_GENERATE_GOLD_IN_ADDITION_TO_STONE = 282, // Stone Miners generate gold in addition to stone
    CIV_BONUS_283_WINGED_HUSSAR_REPLACES_HUSSAR = 283, // Winged Hussar replaces Hussar
    CIV_BONUS_284_CHEMISTRY_AND_HAND_CANNONEER_AVAILABLE_IN_CASTLE = 284, // Chemistry and Hand Cannoneer available in Castle Age
    CIV_BONUS_285_SPEARMEN_DEALS_25_BONUS_DAMAGE = 285, // Spearmen deals +25% bonus damage
    CIV_BONUS_286_FERVOR_AND_SANCTITY_AFFECTS_VILLAGERS = 286, // Fervor and Sanctity affects villagers
    CIV_BONUS_287_CAN_UPGRADE_BOMBARD_CANNONS_TO_HOUFNICE = 287, // Can upgrade Bombard Cannons to Houfnice
    CIV_BONUS_288_CAN_BUILD_CARAVANSERI_IN_IMPERIAL_AGE = 288, // Can build Caravanseri in Imperial Age
    CIV_BONUS_289_GUNPOWDER_UNITS_1_1P_ARMOR = 289, // Gunpowder units +1/+1P armor
    CIV_BONUS_290_RECEIVE_200_WOOD_WHEN_ADVANCING_TO_THE_NEXT_AGE = 290, // Receive +200 wood when advancing to the next age
    CIV_BONUS_291_BARRACKS_TECHNOLOGIES_COST_50 = 291, // Barracks technologies cost -50%
    CIV_BONUS_292_SKIRMISHERS_AND_ELEPHANT_ARCHERS_ATTACK_25_FASTER = 292, // Skirmishers and Elephant Archers attack 25% faster
    CIV_BONUS_293_ELEPHANT_UNITS_RECEIVE_25_LESS_BONUS_DAMAGE = 293, // Elephant units receive 25% less bonus damage and are more resistant to conversion
    CIV_BONUS_294_SHIPS_REGENERATE_15_HP_PER_MINUTE = 294, // Ships regenerate 15 HP per minute
    CIV_BONUS_295_START_WITH_2_FORAGE_BUSHES = 295, // Start with 2 Forage Bushes
    CIV_BONUS_296_CAN_GARRISON_MILLS_WITH_LIVESTOCK_TO_PRODUCE_FOOD = 296, // Can garrison Mills with livestock to produce food
    CIV_BONUS_297_MOUNTED_UNITS_DEAL_20_BONUS_DAMAGE_FEUDAL = 297, // Mounted units deal +20% bonus damage Feudal, +30% Castle, +40% Imperial Age
    CIV_BONUS_298_CAN_GARRISON_DOCKS_WITH_FISHING_SHIPS = 298, // Can garrison Docks with Fishing Ships
    CIV_BONUS_299_CAN_TRAIN_THIRISADAI_IN_DOCKS = 299, // Can train Thirisadai in docks
    CIV_BONUS_300_CAN_RECRUIT_SHRIVAMSHA_RIDERS = 300, // Can recruit Shrivamsha Riders
    CIV_BONUS_301_CAN_RECRUIT_CAMEL_SCOUTS_IN_FEUDAL_AGE = 301, // Can recruit Camel Scouts in Feudal Age
    CIV_BONUS_303_GALLEY_LINE_AND_DROMONS_1_1_ARMOR = 303, // Galley-line and Dromons +1/+1 armor
    CIV_BONUS_304_ELEPHANT_UNITS_1_1P_ARMOR = 304, // Elephant units +1/+1P armor
    CIV_BONUS_305_MONK_UNITS_3_3P_ARMOR = 305, // Monk units +3/+3P armor
    CIV_BONUS_306_INFANTRY_RECEIVES_DOUBLE_EFFECT_FROM_BLACKSMITH_ARMOR = 306, // Infantry receives double effect from Blacksmith armor upgrades
    CIV_BONUS_307_SCORPIONS_COST_60_GOLD_AND_BENEFIT_FROM = 307, // Scorpions cost -60% gold and benefit from Ballistics research
    CIV_BONUS_308_LEGIONARY_REPLACES_TWO_HANDED_SWORDSMAN_CHAMPION = 308, // Legionary replaces Two-Handed Swordsman / Champion
    CIV_BONUS_309_CAN_UPGRADE_HEAVY_SCORPIONS_TO_IMPERIAL_SCORPIONS = 309, // Can upgrade Heavy Scorpions to Imperial Scorpions
    CIV_BONUS_310_CAN_UPGRADE_ELITE_BATTLE_ELEPHANTS_TO_ROYAL = 310, // Can upgrade Elite Battle Elephants to Royal Battle Elephants
    CIV_BONUS_311_CAN_UPGRADE_ELITE_STEPPE_LANCERS_TO_ROYAL_LANCERS = 311, // Can upgrade Elite Steppe Lancers to Royal Lancers
    CIV_BONUS_312_CAVALRY_ARCHERS_2_ATTACK_VS_ARCHERS_EXCEPT = 312, // Cavalry Archers +2 attack vs. Archers (except skirmishers)
    CIV_BONUS_313_WOOD_AND_MINING_UPGRADES_ARE_40_MORE = 313, // Wood and mining upgrades are 40% more effective, economic drop-off buildings cost -25%
    CIV_BONUS_314_FIRST_RELIGIOUS_BUILDING_RECEIVES_A_FREE_RELIC = 314, // First religious building receives a free relic
    CIV_BONUS_315_SAVAR_REPLACES_PALADIN = 315, // Savar replaces Paladin
    CIV_BONUS_316_GALLEY_LINE_AND_DROMONS_FIRE_AN_ADDITIONAL = 316, // Galley-line and Dromons fire an additional projectile
    CIV_BONUS_317_FORTIFIED_CHURCH_REPLACES_MONASTERY = 317, // Fortified church replaces monastery
    CIV_BONUS_318_MULE_CARTS_REPLACE_LUMBER_CAMPS_AND_MINING_CAMPS = 318, // Mule Carts replace Lumber Camps and Mining Camps
    CIV_BONUS_319_START_WITH_A_MULE_CART = 319, // Start with a Mule Cart
    CIV_BONUS_320_RELIGIOUS_BUILDINGS_PROVIDE_VILLAGERS_IN_AN_8 = 320, // Religious buildings provide Villagers in an 8 tile radius with +10% work rate
    CIV_BONUS_321_UNITS_AND_BUILDINGS_RECEIVE_15_DAMAGE_WHEN = 321, // Units and buildings receive -15% damage when fighting from higher elevation
    CIV_BONUS_322_MOUNTED_UNITS_REGENERATE_2_8_14_HP = 322, // Mounted units regenerate 2/8/14 HP per minute, in the Feudal, Castle, Imperial Age
    CIV_BONUS_325_VILLAGERS_WORK_FASTER_WHEN_NEARBY_OTHER_VILLAGERS = 325, // Villagers work faster when nearby other villagers
    CIV_BONUS_327_TRADE_YIELDS_10_STONE_IN_ADDITION_TO_GOLD = 327, // Trade yields 10% stone in addition to gold
    CIV_BONUS_329_CAVALRY_ARCHERS_CAN_DODGE_ONE_PROJECTILE = 329, // Cavalry archers can dodge one projectile
    CIV_BONUS_332_ARCHERY_RANGE_TECHS_COST_50 = 332, // Archery range techs cost -50%
    CIV_BONUS_333_KNIGHTS_AVAILABLE_IN_FEUDAL_AGE_WITH_30HP = 333, // Knights available in Feudal Age with 30HP
    CIV_BONUS_334_SIEGE_TOWERS_CAN_FIRE_ARROWS = 334, // Siege Towers can fire arrows
    CIV_BONUS_335_FIRE_LANCERS_AND_FIRE_SHIPS_MOVE_5 = 335, // Fire Lancers and Fire Ships move +5/10% faster in Castle/Imperial Age
    CIV_BONUS_336_ARCHERY_UNIT_TECHNOLOGIES_AT_THE_ARCHERY_RANGE = 336, // Archery Unit technologies at the Archery Range and Blacksmith cost -25%
    CIV_BONUS_337_SIEGE_WEAPONS_AND_SIEGE_WARSHIPS_MOVE_10 = 337, // Siege Weapons and Siege Warships move +10/15% faster in Castle/Imperial Age
    CIV_BONUS_338_CAN_RECRUIT_WAR_CHARIOTS = 338, // Can recruit War Chariots
    CIV_BONUS_339_GAIN_ACCESS_TO_LIU_BEI = 339, // Gain access to Liu Bei
    CIV_BONUS_340_MILITARY_PRODUCTION_BUILDINGS_AND_DOCKS_PROVIDE_65 = 340, // Military production buildings and Docks provide +65 food
    CIV_BONUS_341_INFANTRY_REGENERATES_10_20_30_HP_PER = 341, // Infantry regenerates 10/20/30 HP per minute in Feudal/Castle/Imperial Age
    CIV_BONUS_342_JIAN_SWORDSMEN_AND_HEI_GUANG_CAVALRY_2 = 342, // Jian Swordsmen and Hei Guang Cavalry +2 attack in Imperial Age
    CIV_BONUS_343_CAREENING_DRY_DOCK_AVAILABLE_ONE_AGE_EARLIER = 343, // Careening, Dry Dock available one age earlier, cost and research time -75%
    CIV_BONUS_344_CAN_RECRUIT_JIAN_SWORDSMEN = 344, // Can recruit Jian Swordsmen
    CIV_BONUS_345_GAIN_ACCESS_TO_SUN_JIAN = 345, // Gain access to Sun Jian
    CIV_BONUS_346_RECEIVE_ONE_FREE_VILLAGER_FOR_EACH_MILL = 346, // Receive one free Villager for each Mill, Lumber- and Mining Camp technology researched
    CIV_BONUS_347_HEI_GUANG_CAVALRY_AND_XIANBEI_RAIDER_15 = 347, // Hei Guang Cavalry and Xianbei Raider +15/30% HP in Castle/Imperial Age
    CIV_BONUS_348_TRACTION_TREBUCHETS_AND_LOU_CHUANS_COST_25 = 348, // Traction Trebuchets and Lou Chuans cost -25%
    CIV_BONUS_349_CAN_RECRUIT_XIANBEI_RAIDERS = 349, // Can recruit Xianbei Raiders
    CIV_BONUS_350_GAIN_ACCESS_TO_CAO_CAO = 350, // Gain access to Cao Cao
    CIV_BONUS_351_MEAT_OF_HUNTED_AND_LIVESTOCK_ANIMALS_DOESN_T_DECAY = 351, // Meat of hunted and livestock animals doesn't decay
    CIV_BONUS_352_MOUNTED_UNITS_AND_FIRE_LANCERS_ATTACK_20 = 352, // Mounted units and Fire Lancers attack +20% faster starting in Feudal Age
    CIV_BONUS_353_SIEGE_ENGINEERS_AVAILABLE_IN_CASTLE_AGE = 353, // Siege Engineers available in Castle Age
    CIV_BONUS_354_SIEGE_AND_FORTIFICATION_UPGRADES_COST_75_WOOD = 354, // Siege and Fortification upgrades cost -75% wood and research +100% faster
    CIV_BONUS_355_UNITS_RECEIVE_50_FRIENDLY_FIRE_DAMAGE = 355, // Units receive -50% friendly fire damage
    CIV_BONUS_356_CAN_RECRUIT_GRENADIERS = 356, // Can recruit Grenadiers
    CIV_BONUS_357_PASTURES_REPLACE_FARMS_AND_MILL_UPGRADES = 357, // Pastures replace Farms and Mill upgrades
    CIV_BONUS_358_SHEPHERDS_AND_HERDERS_GENERATE_10_ADDITIONAL_FOOD = 358, // Shepherds and Herders generate +10% additional food
    CIV_BONUS_359_MELEE_ATTACK_UPGRADE_EFFECTS_ARE_DOUBLED = 359, // Melee attack upgrade effects are doubled
    CIV_BONUS_360_SKIRMISHERS_SPEARMAN_AND_SCOUT_CAVALRY_LINE_TRAIN = 360, // Skirmishers, Spearman- and Scout Cavalry-line train and upgrade +25% faster
    CIV_BONUS_361_HEAVY_CAVALRY_ARCHER_UPGRADE_AVAILABLE_IN_CASTLE = 361, // Heavy Cavalry Archer upgrade available in Castle Age and costs -50%
    CIV_BONUS_362_CAN_TRAIN_MOUNTED_TREBUCHETS = 362, // Can train Mounted Trebuchets
};

#endif // CIV_BONUS_ENUM_H
