name: Build and publish Docker image
on:
  push:
    branches: [main]
  pull_request:
  #  branches: [main]
permissions:
  contents: read
  packages: write

jobs:
  simple-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Simple E2E tests
        run: npm run test:simple
        env:
          CI: true

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: simple-test-results
          path: |
            test-results/
            coverage/
          retention-days: 7

  complex-tests:
    runs-on: ubuntu-latest
    needs: simple-tests  # Run complex tests only if simple tests pass
    services:
      # Run the C++ backend as a Docker service for comprehensive E2E testing
      civbuilder-backend:
        image: ghcr.io/fritz-net/aoe2-civbuilder:latest
        ports:
          - 4000:4000
        env:
          CIVBUILDER_HOSTNAME: http://localhost:4000
        options: --health-cmd="curl -f http://localhost:4000/ || exit 1"
                 --health-interval=30s --health-timeout=10s --health-retries=3
    
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Wait for C++ backend service
        run: |
          echo "Waiting for C++ backend service to be ready..."
          timeout 120 bash -c 'until curl -f http://localhost:4000/ > /dev/null 2>&1; do
            sleep 5; echo "Waiting..."; done' ||
            (echo "Service did not start in time" && exit 1)

      - name: Run Complex E2E tests with C++ Backend
        run: npm run test:complex
        env:
          CI: true
          CIVBUILDER_HOSTNAME: http://localhost:4000

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: complex-test-results
          path: |
            test-results/
            coverage/
          retention-days: 7

  build:
    runs-on: ubuntu-latest
    needs: [simple-tests, complex-tests]  # Only build if both test jobs pass
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up QEMU and Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.build-cpp
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/fritz-net/aoe2-civbuilder:latest,
                ghcr.io/fritz-net/aoe2-civbuilder:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
