name: Build and publish Docker image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up QEMU and Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.build-cpp
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/fritz-net/aoe2-civbuilder:latest,ghcr.io/fritz-net/aoe2-civbuilder:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max